// G3 — the projective geometry everything else rests on.
//
// Every expected value here is hand-computable. That is deliberate: if the
// assertions were generated by running the implementation, a sign error would
// be baked into both and the suite would confirm the bug.

import { test } from "node:test";
import assert from "node:assert/strict";
import { Gnomon } from "./_core.js";

const { geom } = Gnomon;
const near = (a, b, tol = 1e-9) => assert.ok(Math.abs(a - b) <= tol, `${a} !≈ ${b}`);

// A homogeneous vector is only defined up to scale and sign, so comparisons
// normalise and allow either sign.
function sameDirection(actual, expected, tol = 1e-7) {
  const u = geom.unit(Array.from(actual));
  const e = geom.unit(Array.from(expected));
  const dot = Math.abs(u[0] * e[0] + u[1] * e[1] + u[2] * e[2]);
  assert.ok(Math.abs(dot - 1) <= tol, `[${u}] not parallel to [${e}]`);
}

test("a point lies on the line through it", () => {
  const p = geom.point(3, 4);
  const q = geom.point(9, 12);
  const l = geom.lineThrough(p, q);
  // Both generators, and a third collinear point, satisfy l·p = 0.
  near(geom.dot(l, p), 0);
  near(geom.dot(l, q), 0);
  near(geom.dot(l, geom.point(6, 8)), 0);
});

test("two lines meet where they cross", () => {
  // x = 5 and y = 7 cross at (5, 7).
  const vertical = geom.lineThrough(geom.point(5, 0), geom.point(5, 100));
  const horizontal = geom.lineThrough(geom.point(0, 7), geom.point(100, 7));
  const m = geom.dehomogenise(geom.meet(vertical, horizontal));
  near(m.x, 5);
  near(m.y, 7);
});

test("parallel lines meet at infinity and are reported as such", () => {
  const a = geom.lineThrough(geom.point(0, 10), geom.point(100, 10));
  const b = geom.lineThrough(geom.point(0, 90), geom.point(100, 90));
  const m = geom.meet(a, b);

  assert.equal(geom.atInfinity(m), true);
  // The direction survives even though the position does not — this is why the
  // homogeneous form is kept rather than divided through.
  sameDirection(m, [1, 0, 0]);
});

test("dehomogenise refuses rather than returning a huge meaningless number", () => {
  const a = geom.lineThrough(geom.point(0, 10), geom.point(100, 10));
  const b = geom.lineThrough(geom.point(0, 90), geom.point(100, 90));
  assert.equal(geom.dehomogenise(geom.meet(a, b)), null);
});

test("magnitude reports how far out a near-parallel intersection lands", () => {
  // Lines converging by 1 part in 1000 meet about 100_000 px away.
  const a = geom.lineThrough(geom.point(0, 0), geom.point(1000, 0));
  const b = geom.lineThrough(geom.point(0, 1), geom.point(1000, 0.99));
  const m = geom.meet(a, b);
  assert.ok(geom.magnitude(m) > 1e4, `expected a distant meet, got ${geom.magnitude(m)}`);
  assert.ok(Number.isFinite(geom.magnitude(m)));
});

test("Jacobi recovers a diagonal matrix untouched", () => {
  const { values, vectors } = geom.jacobiEigen([[3, 0, 0], [0, 2, 0], [0, 0, 1]]);
  near(values[0], 3);
  near(values[1], 2);
  near(values[2], 1);
  sameDirection(vectors[0], [1, 0, 0]);
  sameDirection(vectors[2], [0, 0, 1]);
});

test("Jacobi recovers a hand-computed non-diagonal case", () => {
  // [[2,1,0],[1,2,0],[0,0,5]] has eigenvalues 5, 3, 1 with eigenvectors
  // e3, [1,1,0]/√2 and [1,-1,0]/√2 — all checkable by hand.
  const { values, vectors } = geom.jacobiEigen([[2, 1, 0], [1, 2, 0], [0, 0, 5]]);
  near(values[0], 5);
  near(values[1], 3);
  near(values[2], 1);
  sameDirection(vectors[0], [0, 0, 1]);
  sameDirection(vectors[1], [1, 1, 0]);
  sameDirection(vectors[2], [1, -1, 0]);
});

test("eigenvalues come back sorted descending", () => {
  const { values } = geom.jacobiEigen([[1, 0, 0], [0, 9, 0], [0, 0, 4]]);
  assert.deepEqual(Array.from(values), [9, 4, 1]);
});

test("two segments give the exact intersection", () => {
  const vp = geom.vanishingPoint([
    { a: [0, 0], b: [500, 300] },
    { a: [0, 600], b: [500, 300] },
  ]);
  const p = geom.dehomogenise(vp.v);
  near(p.x, 500, 1e-6);
  near(p.y, 300, 1e-6);
  // Two lines determine a point exactly: there is no residual to measure.
  near(vp.conditionNumber, 0, 1e-9);
});

test("three concurrent segments give the same point as any two of them", () => {
  const vp = geom.vanishingPoint([
    { a: [0, 0], b: [500, 300] },
    { a: [0, 600], b: [500, 300] },
    { a: [1000, 0], b: [500, 300] },
  ]);
  const p = geom.dehomogenise(vp.v);
  near(p.x, 500, 1e-6);
  near(p.y, 300, 1e-6);
  near(vp.conditionNumber, 0, 1e-9);
  assert.equal(vp.wellConditioned, true);
});

test("condition number rises monotonically as the family stops concurring", () => {
  const drift = [0, 5, 20, 60, 150];
  const conditions = drift.map((d) =>
    geom.vanishingPoint([
      { a: [0, 0], b: [500, 300] },
      { a: [0, 600], b: [500, 300] },
      { a: [1000, 0], b: [500 + d, 300] },
    ]).conditionNumber,
  );

  for (let i = 1; i < conditions.length; i++) {
    assert.ok(
      conditions[i] > conditions[i - 1],
      `condition did not rise: drift ${drift[i - 1]}→${drift[i]} gave ${conditions[i - 1]}→${conditions[i]}`,
    );
  }
  // And the worst case must actually read as poorly conditioned, not merely worse.
  assert.equal(conditions.at(-1) > 0.05, true);
});

test("a parallel family keeps its homogeneous form and is flagged", () => {
  const vp = geom.vanishingPoint([
    { a: [0, 100], b: [1000, 100] },
    { a: [0, 300], b: [1000, 300] },
    { a: [0, 700], b: [1000, 700] },
  ]);
  assert.equal(vp.atInfinity, true);
  assert.equal(vp.point, null);
  sameDirection(vp.v, [1, 0, 0]);
  // Parallel is not the same as poorly conditioned: these lines agree
  // perfectly about their direction, they just meet nowhere finite.
  assert.equal(vp.wellConditioned, true);
});

test("an inconsistent family is reported as unbounded, not merely wide", () => {
  const vp = geom.vanishingPoint([
    { a: [0, 0], b: [1000, 10] },
    { a: [0, 500], b: [1000, 480] },
    { a: [0, 900], b: [1000, 30] },
    { a: [10, 900], b: [900, 950] },
  ]);
  assert.equal(vp.wellConditioned, false);
  assert.equal(vp.unbounded, true);
});

test("scale invariance: the same scene in different pixel units agrees", () => {
  const build = (k) =>
    geom.vanishingPoint([
      { a: [0, 0], b: [500 * k, 300 * k] },
      { a: [0, 600 * k], b: [500 * k, 300 * k] },
      { a: [1000 * k, 0], b: [500 * k, 300 * k] },
    ]);
  // Hartley normalisation is what makes this hold — without it the third
  // component of each line vector is ~k² and swamps the other two.
  const small = geom.dehomogenise(build(1).v);
  const large = geom.dehomogenise(build(8).v);
  near(large.x / 8, small.x, 1e-6);
  near(large.y / 8, small.y, 1e-6);
});

test("fewer than two segments is an error, not a guess", () => {
  assert.throws(() => geom.vanishingPoint([{ a: [0, 0], b: [1, 1] }]), /at least two/);
});
